FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY etl/{{.ProjectName}}.Etl.csproj .
RUN dotnet restore

COPY etl/ .
RUN dotnet publish -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "{{.DotnetNamespace}}.Etl.dll"]
